<a href="https://colab.research.google.com/github/adhii1144/BigData/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [ ]:
arr = np.array([1,2,3,4])

In [ ]:
arr

array([1, 2, 3, 4])

In [ ]:
np.version

<module 'numpy.version' from '/usr/local/lib/python3.10/dist-packages/numpy/version.py'>

In [ ]:
arr1 = np.array((1,2,3,4,6))
arr1

array([1, 2, 3, 4, 6])

In [ ]:
type(arr1)

numpy.ndarray

In [ ]:
odarray = np.array(12)
odarray

array(12)

In [ ]:
onedaray = np.array([1,2,3,4,5])
onedaray

array([1, 2, 3, 4, 5])

In [ ]:
twodarray = np.array([[1,2,3,4],
                      [4,5,6,7]])
twodarray

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [ ]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
arr

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [ ]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [ ]:
arr = np.array([1,2,3,4,5])
print(arr[0])
print(arr[1])
print(arr[2])
print(arr[3])
print(arr[4])

1
2
3
4
5


In [ ]:
arr[2] + arr[1]

5

In [3]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
arr


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [4]:
arr[1][1]

7

In [5]:
arr[0,2]

3